baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[params.socialIcons]]
name = "github"
url = "https://github.com/jakobhellermann"

[[params.socialIcons]]
name = "Rss"
url = "/index.xml"

[module]

[[module.imports]]
path = "github.com/hugo-sid/hugo-blog-awesome"
